### PR TITLE
Improve advanced_driving skill

### PR DESCRIPTION
**Pull request by minhduc0711**
# Summary
This PR extends the `advanced_driving` skill with three main improvements:
* **Variable vehicle width**: in particular, they can occupy more than one lane at a time. Used for simulating different vehicle types.
* **More realistic vehicle movement**: now use [Intelligent Driver Model](https://traffic-simulation.de/info/info_IDM.html) for acceleration computation and [MOBIL](https://traffic-simulation.de/info/info_MOBIL.html) for lane changing.
* **Ignoring one-way roads**: can be toggled via an attribute, which allows vehicles to move in the opposite direction on a one-way road (i.e. a directed edge). This feature is adapted from the `side_driving` skill from the ESCAPE project, and one possible use is to simulate pedestrians, who are not restricted by one-way roads.

Note that while this version is intended to be compatible with existing GAML models, it will break every skill that subclasses `DrivingSkill`, since lots of internal private methods have been changed.

# Changelog
### Variable vehicle width
This introduces several new attributes:
* `lowest_lane` (`int`): the lane with the smallest index that the vehicle is currently occupying.
* `num_lanes_occupied` (`int`): the number of lanes that the vehicle occupies (i.e. its width).

Deprecated attributes:
* `current_lane`: deprecated in favor of `lowest_lane`, and will point to that attribute instead.
* `on_linked_road`: deprecated in favor of `using_linked_road`, and will point to that attribute instead.

### Intelligent Driver Model
The characteristics and behavior of each vehicle can be controlled using a set of parameters. More details can be found [here](https://traffic-simulation.de/info/info_IDM.html#IDMparameters).
* `max_speed` (`float`): desired speed *v0*
* `max_time_headway` (`float`): time headway *T*
* `min_safety_distance` (`float`): minimum gap *s0*
* `max_acceleration` (`float`): acceleration *a*
* `max_deceleration` (`float`): deceleration *b*
* `delta_idm` (`float`): the exponent delta used in the model equation

These attributes were added for debugging purposes, but they can be somewhat informative for users:
* `leading_vehicle` (`agent`): the vehicle that is directly in front of the current vehicle (i.e. they share at least one lane, and there is no vehicle between them)
	* This can be a "road_node" agent, which can be considered as a zero-length stopping vehicle; this allows simulating vehicles stopping at intersections (e.g. red lights).
	* This can also be `nil`, meaning that the leading vehicle is too far ahead, or there is none.
* `leading_distance` (`float`): the bumper-to-bumper distance between the current vehicle and the leading vehicle
* `leading_speed` (`float`): the speed of the leading vehicle

Deprecated attributes:
* `real_speed`: the speed of a vehicle is computed only once with IDM, so having both `speed` and `real_speed` is not necessary anymore. This now points to the value of `speed`.

### MOBIL lane change model
Also comes with a set of parameters to control each vehicle's lane change behavior. More info at [this link](https://traffic-simulation.de/info/info_MOBIL.html).
* `politeness_factor` (`float`): politeness factor *p*
* `max_safe_deceleration` (`float`): maximum safe deceleration *b_save*
* `acc_gain_threshold` (`float`): threshold *a_thr*
* `acc_bias` (`float`): bias to the right (or left) lane 

In addition, a few custom attributes related to lane change were added:
* `lane_change_limit` (`int`): the maximum "lane range" when switching lanes during segments traversal. For example, if `lane_change_limit=2`, the vehicle can only consider switching to lanes with indices in the range `[lowest_lane - 2, lowest_lane + 2]`.
* `linked_lane_limit` (`int`): the maximum number of lanes on the linked road that the vehicle is allowed to use.
* `using_linked_road` (`boolean`): a read-only attribute that indicates if the vehicle is using at least one lane on the linked road.
* `allowed_lanes` (`list<int>`): contains the indices of the lanes which the vehicle will only be able to use
* `lane_change_cooldown` (`float`): the minimum amount of time the vehicle must wait during lane changes
* `time_since_lane_change` (`float`): the time elapsed since the last lane change

Deprecated attributes:
* `on_linked_road`: deprecated in favor of `using_linked_road`, and will point to that attribute instead.
* `proba_change_lane_down`: deprecated because this attribute highly correlates with `acc_bias`
* `proba_change_lane_up`: same as `proba_change_lane_down`

### Ignoring one-way roads
New attributes:
* `ignore_oneway` (`boolean`): if set to `true`, the vehicle will be able to move in the wrong direction on a directed road.
* `violating_oneway` (`boolean`): indicates if the vehicle is violating a one-way road.

### Other
New actions:
* `on_entering_new_road`: override this "hook" to do something right as the vehicle enters a new road (e.g. adjust some attributes related to lane changing with respect to the road width).

Deprecated actions:
* `speed_choice`: deprecated due to the use of IDM, will do nothing if overridden.
* `lane_choice`: deprecated due to the use of MOBIL, will do nothing if overridden.
* `advanced_follow_driving`: deprecated because it does not do what is described in its documentation
* `compute_path_from_nodes`: merged with `compute_path` (usage: `compute_path nodes: list_of_nodes`).

## `road` skill
New attributes:
* `num_segments` (`int`): read-only, the number of segments composing the road

### `moving` skill
* Fix incorrect `heading` update.
* Make setters and getters for `speed`, `real_speed` and `current_path` static.

# TODOs:
- [x] Update logic when driving on non-linked roads
- [x] Update logic when driving on linked roads
- [x] Integrate IDM and MOBIL?
- [x] Integrate "side driving" from ESCAPE project

### CODE REVIEW

**Comment by hqnghi88** [comment]
hello Duc,
You are requesting to merge your branch into master branch, but in your commits, there are many things belong to 1.8.2 branch of gama, which is modified to adapt with jdk 15. This 1.8.2 branch is still in alpha phase, we need to test it more. So if we merge your request into master, it require @AlexisDrogoul to confirm that we change now, officially, to work, develop on jdk15.

**Comment by minhduc0711** [comment]
@hqnghi88 yes I understand. This is a draft PR anyway, right now I'm just putting it here to take notes of what I have changed.
I will ask for approval to merge this after the 1.8.2 branch has been merged.

**Comment by AlexisDrogoul** [comment]
I confirm it would be better, yes. We just need to check if all the commit to master have been moved to 1.8.2.

**Comment by minhduc0711** [comment]
@hqnghi88 plz reopen :fearful:

**Comment by hqnghi88** [comment]
Sorry, miss touching.

**Comment by minhduc0711** [comment]
@AlexisDrogoul @ptaillandier I think this one is ready to merge.

**Pull request merged**
